export {};

declare global {
	namespace NodeJS {
		interface ProcessEnv {
			NODE_ENV
			KAFKA_HOST
			KAFKA_RETRIES
			KAFKA_INITIAL_RETRY_TIME
			KAFKA_RETRY_MULTIPLIER
			KAFKA_MAX_RETRY_TIME
			LEADERBOARD_SERVICE_KAFKA_GROUP_ID
			LOGSMANAGEMENT_SERVICE_KAFKA_GROUP_ID
			PLAYERS_REPO_HOST
			SCORES_REPO_HOST
			LOGS_REPO_HOST
			GAME_SCORES_SERVICE_PORT
			LEADERBOARD_SERVICE_PORT
			LOGSMANAGEMENT_SERVICE_PORT
			PLAYERSMANAGEMENT_SERVICE_PORT
			REDIS_HOST
			REDIS_PORT
			INTERNAL_API_TOKEN
			GAME_SCORES_SERVICE_HOST
			PLAYERS_MANAGEMENT_SERVICE_HOST
			TOPIC_SCORE_SUBMITTED
			TOPIC_LOGS_RAW
			REDIS_KEY_LEADERBOARD
			LOG_DATA_MIN_CHARS
			LOG_DATA_MAX_CHARS
			LOGSMANAGEMENT_TOKENS_PER_SECOND
			LOGSMANAGEMENT_MAX_TOKENS
		}
	}
}
